alter table public.vendedor
  alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.vendedor', 'id'),
  coalesce((select max(id) from public.vendedor), 1),
  true
);

alter table public.metodo_pago
  alter column id set default gen_random_uuid()::text;
