alter table public.producto
  add column if not exists precio_costo numeric(12,2) not null default 0;

create table if not exists public.platos_ingredientes (
  id bigint generated by default as identity primary key,
  plato_id bigint not null references public.producto(id) on delete cascade,
  ingrediente_id bigint not null references public.ingredientes(id),
  cantidad_usada numeric(12,3) not null check (cantidad_usada > 0)
);

create table if not exists public.platos_subplatos (
  id bigint generated by default as identity primary key,
  plato_padre_id bigint not null references public.producto(id) on delete cascade,
  plato_hijo_id bigint not null references public.producto(id),
  cantidad_usada numeric(12,3) not null check (cantidad_usada > 0),
  constraint platos_subplatos_no_self check (plato_padre_id <> plato_hijo_id)
);

create unique index if not exists platos_ingredientes_unique_idx
  on public.platos_ingredientes (plato_id, ingrediente_id);

create unique index if not exists platos_subplatos_unique_idx
  on public.platos_subplatos (plato_padre_id, plato_hijo_id);

alter table public.platos_ingredientes enable row level security;
alter table public.platos_subplatos enable row level security;

drop policy if exists "bootstrap_allow_all_platos_ingredientes" on public.platos_ingredientes;
create policy "bootstrap_allow_all_platos_ingredientes"
  on public.platos_ingredientes
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "bootstrap_allow_all_platos_subplatos" on public.platos_subplatos;
create policy "bootstrap_allow_all_platos_subplatos"
  on public.platos_subplatos
  for all
  to anon, authenticated
  using (true)
  with check (true);

create or replace function public.plato_tiene_descendiente(
  p_origen bigint,
  p_buscado bigint
)
returns boolean
language sql
stable
as $$
  with recursive descendientes as (
    select ps.plato_hijo_id
    from public.platos_subplatos ps
    where ps.plato_padre_id = p_origen
    union
    select ps.plato_hijo_id
    from public.platos_subplatos ps
    join descendientes d on d.plato_hijo_id = ps.plato_padre_id
  )
  select exists(select 1 from descendientes where plato_hijo_id = p_buscado);
$$;

create or replace function public.calcular_costo_plato(
  p_id bigint,
  p_visitados bigint[] default '{}'
)
returns numeric
language plpgsql
stable
as $$
declare
  v_total numeric := 0;
  v_item record;
begin
  if p_id = any(coalesce(p_visitados, '{}')) then
    raise exception 'Se detecto un ciclo al calcular el costo del plato %', p_id;
  end if;

  for v_item in
    select pi.cantidad_usada, i.cantidad_base, i.precio_costo_base
    from public.platos_ingredientes pi
    join public.ingredientes i on i.id = pi.ingrediente_id
    where pi.plato_id = p_id
      and coalesce(i.deleted, false) = false
  loop
    if coalesce(v_item.cantidad_base, 0) <= 0 then
      continue;
    end if;

    v_total := v_total + ((v_item.precio_costo_base / v_item.cantidad_base) * v_item.cantidad_usada);
  end loop;

  for v_item in
    select ps.plato_hijo_id, ps.cantidad_usada
    from public.platos_subplatos ps
    join public.producto p on p.id = ps.plato_hijo_id
    where ps.plato_padre_id = p_id
      and p.tipo = 'PLATO'
      and coalesce(p.deleted, false) = false
  loop
    v_total := v_total + (public.calcular_costo_plato(v_item.plato_hijo_id, array_append(coalesce(p_visitados, '{}'), p_id)) * v_item.cantidad_usada);
  end loop;

  return round(coalesce(v_total, 0), 2);
end;
$$;

create or replace function public.plato_to_json(p_id bigint)
returns jsonb
language sql
stable
as $$
  with plato as (
    select p.*
    from public.producto p
    where p.id = p_id
      and p.tipo = 'PLATO'
      and coalesce(p.deleted, false) = false
  )
  select jsonb_build_object(
    'id', p.id,
    'codigo', p.codigo,
    'nombre', p.nombre,
    'descripcion', p.descripcion,
    'precio', coalesce(p.precio, 0),
    'precioCosto', public.calcular_costo_plato(p.id),
    'stock', coalesce(p.stock, 0),
    'ingredientes', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', pi.id,
          'ingredienteId', i.id,
          'cantidadUsada', pi.cantidad_usada,
          'ingrediente', jsonb_build_object(
            'id', i.id,
            'nombre', i.nombre,
            'unidadBase', i.unidad_base,
            'cantidadBase', i.cantidad_base,
            'precioCostoBase', i.precio_costo_base,
            'codigo', i.codigo
          )
        )
        order by pi.id
      )
      from public.platos_ingredientes pi
      join public.ingredientes i on i.id = pi.ingrediente_id
      where pi.plato_id = p.id
        and coalesce(i.deleted, false) = false
    ), '[]'::jsonb),
    'subplatos', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', ps.id,
          'platoHijoId', h.id,
          'cantidadUsada', ps.cantidad_usada,
          'platoHijo', jsonb_build_object(
            'id', h.id,
            'codigo', h.codigo,
            'nombre', h.nombre,
            'precio', coalesce(h.precio, 0),
            'precioCosto', public.calcular_costo_plato(h.id),
            'stock', coalesce(h.stock, 0)
          )
        )
        order by ps.id
      )
      from public.platos_subplatos ps
      join public.producto h on h.id = ps.plato_hijo_id
      where ps.plato_padre_id = p.id
        and h.tipo = 'PLATO'
        and coalesce(h.deleted, false) = false
    ), '[]'::jsonb)
  )
  from plato p;
$$;

create or replace function public.platos_listar()
returns setof jsonb
language sql
stable
as $$
  select public.plato_to_json(p.id)
  from public.producto p
  where p.tipo = 'PLATO'
    and coalesce(p.deleted, false) = false
  order by p.nombre, p.id;
$$;

create or replace function public.platos_detalle(p_id bigint)
returns jsonb
language sql
stable
as $$
  select public.plato_to_json(p_id);
$$;

create or replace function public.platos_crear(payload jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_plato_id bigint;
  v_item jsonb;
begin
  if coalesce(trim(payload->>'codigo'), '') = '' then
    raise exception 'El codigo del plato es obligatorio';
  end if;

  insert into public.producto (tipo, codigo, nombre, descripcion, precio, stock, precio_costo, deleted)
  values (
    'PLATO',
    trim(payload->>'codigo'),
    trim(coalesce(payload->>'nombre', '')),
    nullif(trim(coalesce(payload->>'descripcion', '')), ''),
    coalesce((payload->>'precio')::numeric, 0),
    coalesce((payload->>'stock')::integer, 0),
    0,
    false
  )
  returning id into v_plato_id;

  for v_item in
    select value from jsonb_array_elements(coalesce(payload->'ingredientes', '[]'::jsonb))
  loop
    insert into public.platos_ingredientes (plato_id, ingrediente_id, cantidad_usada)
    values (
      v_plato_id,
      (v_item->>'ingredienteId')::bigint,
      coalesce((v_item->>'cantidadUsada')::numeric, 0)
    );
  end loop;

  for v_item in
    select value from jsonb_array_elements(coalesce(payload->'subplatos', '[]'::jsonb))
  loop
    if (v_item->>'platoHijoId')::bigint = v_plato_id then
      raise exception 'Un plato no puede contenerse a si mismo';
    end if;

    if public.plato_tiene_descendiente((v_item->>'platoHijoId')::bigint, v_plato_id) then
      raise exception 'El subplato % generaria un ciclo', (v_item->>'platoHijoId');
    end if;

    insert into public.platos_subplatos (plato_padre_id, plato_hijo_id, cantidad_usada)
    values (
      v_plato_id,
      (v_item->>'platoHijoId')::bigint,
      coalesce((v_item->>'cantidadUsada')::numeric, 0)
    );
  end loop;

  update public.producto
  set precio_costo = public.calcular_costo_plato(v_plato_id)
  where id = v_plato_id;

  return public.plato_to_json(v_plato_id);
end;
$$;

create or replace function public.platos_actualizar(p_id bigint, payload jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_item jsonb;
begin
  update public.producto
  set
    codigo = trim(coalesce(payload->>'codigo', codigo)),
    nombre = trim(coalesce(payload->>'nombre', nombre)),
    descripcion = case
      when payload ? 'descripcion' then nullif(trim(coalesce(payload->>'descripcion', '')), '')
      else descripcion
    end,
    precio = case when payload ? 'precio' then coalesce((payload->>'precio')::numeric, 0) else precio end,
    stock = case when payload ? 'stock' then coalesce((payload->>'stock')::integer, 0) else stock end
  where id = p_id
    and tipo = 'PLATO'
    and coalesce(deleted, false) = false;

  if not found then
    raise exception 'Plato % no encontrado', p_id;
  end if;

  delete from public.platos_ingredientes where plato_id = p_id;
  delete from public.platos_subplatos where plato_padre_id = p_id;

  for v_item in
    select value from jsonb_array_elements(coalesce(payload->'ingredientes', '[]'::jsonb))
  loop
    insert into public.platos_ingredientes (plato_id, ingrediente_id, cantidad_usada)
    values (
      p_id,
      (v_item->>'ingredienteId')::bigint,
      coalesce((v_item->>'cantidadUsada')::numeric, 0)
    );
  end loop;

  for v_item in
    select value from jsonb_array_elements(coalesce(payload->'subplatos', '[]'::jsonb))
  loop
    if (v_item->>'platoHijoId')::bigint = p_id then
      raise exception 'Un plato no puede contenerse a si mismo';
    end if;

    if public.plato_tiene_descendiente((v_item->>'platoHijoId')::bigint, p_id) then
      raise exception 'El subplato % generaria un ciclo', (v_item->>'platoHijoId');
    end if;

    insert into public.platos_subplatos (plato_padre_id, plato_hijo_id, cantidad_usada)
    values (
      p_id,
      (v_item->>'platoHijoId')::bigint,
      coalesce((v_item->>'cantidadUsada')::numeric, 0)
    );
  end loop;

  update public.producto
  set precio_costo = public.calcular_costo_plato(p_id)
  where id = p_id;

  return public.plato_to_json(p_id);
end;
$$;

create or replace function public.platos_borrar(p_id bigint)
returns jsonb
language plpgsql
as $$
declare
  v_result jsonb;
begin
  v_result := public.plato_to_json(p_id);

  update public.producto
  set deleted = true
  where id = p_id
    and tipo = 'PLATO';

  return v_result;
end;
$$;
