create extension if not exists pgcrypto;

create table if not exists public.producto (
  id bigint generated by default as identity primary key,
  tipo varchar(50) not null default 'PRODUCTO',
  codigo varchar(100) not null unique,
  nombre text not null,
  descripcion text null,
  precio numeric(10, 2) not null default 0,
  stock integer not null default 0,
  deleted boolean not null default false
);

create table if not exists public.cliente (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellido text null,
  email text null,
  telefono text null,
  direccion text null,
  deleted boolean not null default false
);

create table if not exists public.vendedor (
  id bigint generated by default as identity primary key,
  nombre text not null,
  deleted boolean not null default false
);

create table if not exists public.metodo_pago (
  id varchar(100) primary key default gen_random_uuid()::text,
  nombre text not null,
  tipo varchar(20) not null check (tipo in ('debito', 'credito', 'efectivo', 'pendiente', 'usd', 'otro')),
  deleted boolean not null default false
);

create table if not exists public.item_venta (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text null,
  precio numeric(10, 2) not null,
  cantidad integer not null default 1,
  codigo varchar(100) not null
);

create table if not exists public.venta (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  cliente_id bigint not null references public.cliente(id),
  vendedor_id bigint null references public.vendedor(id) on delete set null,
  total numeric(10, 2) not null default 0,
  deleted boolean not null default false
);

create table if not exists public.venta_detalle (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.venta(id) on delete cascade,
  item_id bigint not null references public.item_venta(id) on delete cascade
);

create table if not exists public.venta_pago (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.venta(id) on delete cascade,
  metodo_id varchar(100) not null references public.metodo_pago(id),
  monto numeric(10, 2) not null,
  cuotas integer null
);

create table if not exists public.caja (
  id text primary key default 'main',
  saldo_pesos numeric(12, 2) not null default 0,
  saldo_usd numeric(12, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.caja_move_detail (
  id bigint generated by default as identity primary key,
  saldo_pesos numeric(12, 2) not null default 0,
  saldo_usd numeric(12, 2) not null default 0,
  move_type varchar(10) not null check (move_type in ('in', 'out')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.horario (
  id bigint generated by default as identity primary key,
  hora_ingreso timestamptz not null default now(),
  hora_egreso timestamptz null,
  vendedor_id bigint null references public.vendedor(id)
);

create table if not exists public.movimiento_stock (
  id bigint generated by default as identity primary key,
  products_move_stock jsonb not null default '[]'::jsonb,
  fecha timestamptz not null default now(),
  move_type varchar(10) not null check (move_type in ('in', 'out')),
  deleted boolean not null default false
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  auth_id text not null unique,
  paymenth_date timestamptz not null default now(),
  venc_date timestamptz not null default now(),
  deleted boolean not null default false
);

create table if not exists public.ingredientes (
  id bigint generated by default as identity primary key,
  nombre varchar(150) not null,
  unidad_base varchar(30) not null check (unidad_base in ('UNIDAD', 'GRAMOS', 'MILILITROS')),
  cantidad_base numeric(12, 3) not null,
  codigo varchar(100) not null unique,
  precio_costo_base numeric(12, 2) not null,
  deleted boolean not null default false
);

insert into public.caja (id, saldo_pesos, saldo_usd)
values ('main', 0, 0)
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_caja_updated_at on public.caja;
create trigger trg_caja_updated_at
before update on public.caja
for each row
execute function public.set_updated_at();

drop trigger if exists trg_caja_move_detail_updated_at on public.caja_move_detail;
create trigger trg_caja_move_detail_updated_at
before update on public.caja_move_detail
for each row
execute function public.set_updated_at();

alter table public.producto enable row level security;
alter table public.cliente enable row level security;
alter table public.vendedor enable row level security;
alter table public.metodo_pago enable row level security;
alter table public.item_venta enable row level security;
alter table public.venta enable row level security;
alter table public.venta_detalle enable row level security;
alter table public.venta_pago enable row level security;
alter table public.caja enable row level security;
alter table public.caja_move_detail enable row level security;
alter table public.horario enable row level security;
alter table public.movimiento_stock enable row level security;
alter table public.users enable row level security;
alter table public.ingredientes enable row level security;

drop policy if exists "bootstrap_all_producto" on public.producto;
create policy "bootstrap_all_producto" on public.producto for all using (true) with check (true);

drop policy if exists "bootstrap_all_cliente" on public.cliente;
create policy "bootstrap_all_cliente" on public.cliente for all using (true) with check (true);

drop policy if exists "bootstrap_all_vendedor" on public.vendedor;
create policy "bootstrap_all_vendedor" on public.vendedor for all using (true) with check (true);

drop policy if exists "bootstrap_all_metodo_pago" on public.metodo_pago;
create policy "bootstrap_all_metodo_pago" on public.metodo_pago for all using (true) with check (true);

drop policy if exists "bootstrap_all_item_venta" on public.item_venta;
create policy "bootstrap_all_item_venta" on public.item_venta for all using (true) with check (true);

drop policy if exists "bootstrap_all_venta" on public.venta;
create policy "bootstrap_all_venta" on public.venta for all using (true) with check (true);

drop policy if exists "bootstrap_all_venta_detalle" on public.venta_detalle;
create policy "bootstrap_all_venta_detalle" on public.venta_detalle for all using (true) with check (true);

drop policy if exists "bootstrap_all_venta_pago" on public.venta_pago;
create policy "bootstrap_all_venta_pago" on public.venta_pago for all using (true) with check (true);

drop policy if exists "bootstrap_all_caja" on public.caja;
create policy "bootstrap_all_caja" on public.caja for all using (true) with check (true);

drop policy if exists "bootstrap_all_caja_move_detail" on public.caja_move_detail;
create policy "bootstrap_all_caja_move_detail" on public.caja_move_detail for all using (true) with check (true);

drop policy if exists "bootstrap_all_horario" on public.horario;
create policy "bootstrap_all_horario" on public.horario for all using (true) with check (true);

drop policy if exists "bootstrap_all_movimiento_stock" on public.movimiento_stock;
create policy "bootstrap_all_movimiento_stock" on public.movimiento_stock for all using (true) with check (true);

drop policy if exists "bootstrap_all_users" on public.users;
create policy "bootstrap_all_users" on public.users for all using (true) with check (true);

drop policy if exists "bootstrap_all_ingredientes" on public.ingredientes;
create policy "bootstrap_all_ingredientes" on public.ingredientes for all using (true) with check (true);
